name: 'check-notebooks'

on:
  pull_request:
    branches:
      - main

jobs:
  check-notebooks:
    name: check-notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
