name: 'check-notebooks'

on:
  pull_request:
    branches:
      - main

jobs:
  check-notebooks:
    name: check-notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Ensure clean notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
